name: check
on: ['push']

jobs:
  check:
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: mvn verify
        run: mvn clean verify
